openapi: 3.0.0
info:
  title: Especificação para criação da conta do usuário
  description: Especificação para criação da conta do usuário
  contact:
    email: diegoalves123@gmail.com
  version: 1.0.0
servers:
- url: /
security:
- application:
  - read
  - write
paths:
  /accounts:
    get:
      summary: Recuperar todas as contas
      parameters:
      - name: token
        in: header
        description: Token JWT no header
        required: true
        style: simple
        explode: false
        schema:
          type: array
          items:
            type: string
            format: string
        example: ijMqSfD6+grE5PhMqz0cWcUU1+h+OZ7lbaFPRX2ym1bqCEe/1Fvjbq1paWSW80fip723tL+E1m0r7vLjdwMabcn7wAfUS6TSgj2qA5yF2YA++L/lEFnPDrFAF/rOt36q2Emi6ABf0fn21SE6zKIGX6PjGK+j7wkb9GayN4KUYynHclvIpL9TWXxRLsMEww9t8H8TMOfLaYo/aJtS/5cNMOlFCodf85WRlyAwUEfnwiXDbng1SoGmos8RR8njyLOoi8JCostvlOobdjpt34hgrhDSs/CyS91nUHbOU6hnxiQWkfuT5+cV/feN3gWd6BGs3Yxmxhkcg0iaYaJUNF5U1c8zzG/yqmHsk/evvN3MQM6S9BKyE4kP8rHoeK0rAQJzeQe9hwlCMpy+lB4WAcrwv04y7hrGyBOJOj5nDeRS8ruvJdtIrPqRz7lOEODuQ5MafbLfw9OT/+lml7dyfRwZkjuaoql9qYcGqkf+n2XBYkBVrQrmbwBVEF2VrdaDVVGjyPKwvOKUFzu8ao+ut6vlOdtvtDN152NSiiewubtMJWelxamppaYVLWlYIT2eTnasuKuyrw0Z4tLttktq2p0hkCRqjTeC5zWC7EIqN/p7gYU+vBRC3OhVS2FrTWaM+5upZvrbNPLLUgZhOgIogbGDUklJ7Z7zUpXpVKrJ+8LSgCxeRoiKPNWSCbU8PxJIGd/zOFHh4Rzp4GHNGfThDYgjkK80y3ct4R4hjR/aiho9k/g=
      responses:
        "200":
          description: ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/body_response'
        "400":
          description: Dados do request enviados incorretos
        "401":
          description: "Token inválido, inexixtente ou expirado"
        "500":
          description: Erro no servidor
    post:
      summary: Criar uma nova conta
      parameters:
      - name: token
        in: header
        description: Token JWT no header
        required: true
        style: simple
        explode: false
        schema:
          type: array
          items:
            type: string
            format: string
        example: ijMqSfD6+grE5PhMqz0cWcUU1+h+OZ7lbaFPRX2ym1bqCEe/1Fvjbq1paWSW80fip723tL+E1m0r7vLjdwMabcn7wAfUS6TSgj2qA5yF2YA++L/lEFnPDrFAF/rOt36q2Emi6ABf0fn21SE6zKIGX6PjGK+j7wkb9GayN4KUYynHclvIpL9TWXxRLsMEww9t8H8TMOfLaYo/aJtS/5cNMOlFCodf85WRlyAwUEfnwiXDbng1SoGmos8RR8njyLOoi8JCostvlOobdjpt34hgrhDSs/CyS91nUHbOU6hnxiQWkfuT5+cV/feN3gWd6BGs3Yxmxhkcg0iaYaJUNF5U1c8zzG/yqmHsk/evvN3MQM6S9BKyE4kP8rHoeK0rAQJzeQe9hwlCMpy+lB4WAcrwv04y7hrGyBOJOj5nDeRS8ruvJdtIrPqRz7lOEODuQ5MafbLfw9OT/+lml7dyfRwZkjuaoql9qYcGqkf+n2XBYkBVrQrmbwBVEF2VrdaDVVGjyPKwvOKUFzu8ao+ut6vlOdtvtDN152NSiiewubtMJWelxamppaYVLWlYIT2eTnasuKuyrw0Z4tLttktq2p0hkCRqjTeC5zWC7EIqN/p7gYU+vBRC3OhVS2FrTWaM+5upZvrbNPLLUgZhOgIogbGDUklJ7Z7zUpXpVKrJ+8LSgCxeRoiKPNWSCbU8PxJIGd/zOFHh4Rzp4GHNGfThDYgjkK80y3ct4R4hjR/aiho9k/g=
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/body_request'
        required: true
      responses:
        "201":
          description: Criado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/body_response'
        "400":
          description: Dados do request enviados incorretos
        "401":
          description: "Token inválido, inexixtente ou expirado"
        "500":
          description: Erro no servidor
  /accounts/{id}:
    get:
      summary: Recuperar uma conta de usuário pelo id
      parameters:
      - name: id
        in: path
        description: id da conta do usuário
        required: true
        style: simple
        explode: false
        schema:
          type: integer
      - name: token
        in: header
        description: Token JWT no header
        required: true
        style: simple
        explode: false
        schema:
          type: array
          items:
            type: string
            format: string
        example: ijMqSfD6+grE5PhMqz0cWcUU1+h+OZ7lbaFPRX2ym1bqCEe/1Fvjbq1paWSW80fip723tL+E1m0r7vLjdwMabcn7wAfUS6TSgj2qA5yF2YA++L/lEFnPDrFAF/rOt36q2Emi6ABf0fn21SE6zKIGX6PjGK+j7wkb9GayN4KUYynHclvIpL9TWXxRLsMEww9t8H8TMOfLaYo/aJtS/5cNMOlFCodf85WRlyAwUEfnwiXDbng1SoGmos8RR8njyLOoi8JCostvlOobdjpt34hgrhDSs/CyS91nUHbOU6hnxiQWkfuT5+cV/feN3gWd6BGs3Yxmxhkcg0iaYaJUNF5U1c8zzG/yqmHsk/evvN3MQM6S9BKyE4kP8rHoeK0rAQJzeQe9hwlCMpy+lB4WAcrwv04y7hrGyBOJOj5nDeRS8ruvJdtIrPqRz7lOEODuQ5MafbLfw9OT/+lml7dyfRwZkjuaoql9qYcGqkf+n2XBYkBVrQrmbwBVEF2VrdaDVVGjyPKwvOKUFzu8ao+ut6vlOdtvtDN152NSiiewubtMJWelxamppaYVLWlYIT2eTnasuKuyrw0Z4tLttktq2p0hkCRqjTeC5zWC7EIqN/p7gYU+vBRC3OhVS2FrTWaM+5upZvrbNPLLUgZhOgIogbGDUklJ7Z7zUpXpVKrJ+8LSgCxeRoiKPNWSCbU8PxJIGd/zOFHh4Rzp4GHNGfThDYgjkK80y3ct4R4hjR/aiho9k/g=
      responses:
        "200":
          description: ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/body_response'
        "400":
          description: Dados do request enviados incorretos
        "401":
          description: "Token inválido, inexixtente ou expirado"
        "404":
          description: "Recurso {id} não encontado"
        "500":
          description: Erro no servidor
    put:
      summary: Atualizar uma conta de usuário pelo id
      parameters:
      - name: id
        in: path
        description: id da conta do usuário
        required: true
        style: simple
        explode: false
        schema:
          type: integer
      - name: token
        in: header
        description: Token JWT no header
        required: true
        style: simple
        explode: false
        schema:
          type: array
          items:
            type: string
            format: string
        example: ijMqSfD6+grE5PhMqz0cWcUU1+h+OZ7lbaFPRX2ym1bqCEe/1Fvjbq1paWSW80fip723tL+E1m0r7vLjdwMabcn7wAfUS6TSgj2qA5yF2YA++L/lEFnPDrFAF/rOt36q2Emi6ABf0fn21SE6zKIGX6PjGK+j7wkb9GayN4KUYynHclvIpL9TWXxRLsMEww9t8H8TMOfLaYo/aJtS/5cNMOlFCodf85WRlyAwUEfnwiXDbng1SoGmos8RR8njyLOoi8JCostvlOobdjpt34hgrhDSs/CyS91nUHbOU6hnxiQWkfuT5+cV/feN3gWd6BGs3Yxmxhkcg0iaYaJUNF5U1c8zzG/yqmHsk/evvN3MQM6S9BKyE4kP8rHoeK0rAQJzeQe9hwlCMpy+lB4WAcrwv04y7hrGyBOJOj5nDeRS8ruvJdtIrPqRz7lOEODuQ5MafbLfw9OT/+lml7dyfRwZkjuaoql9qYcGqkf+n2XBYkBVrQrmbwBVEF2VrdaDVVGjyPKwvOKUFzu8ao+ut6vlOdtvtDN152NSiiewubtMJWelxamppaYVLWlYIT2eTnasuKuyrw0Z4tLttktq2p0hkCRqjTeC5zWC7EIqN/p7gYU+vBRC3OhVS2FrTWaM+5upZvrbNPLLUgZhOgIogbGDUklJ7Z7zUpXpVKrJ+8LSgCxeRoiKPNWSCbU8PxJIGd/zOFHh4Rzp4GHNGfThDYgjkK80y3ct4R4hjR/aiho9k/g=
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/body_request'
        required: true
      responses:
        "202":
          description: Aceito
        "400":
          description: Dados do request enviados incorretos
        "401":
          description: "Token inválido, inexixtente ou expirado"
        "404":
          description: "Recurso {id} não encontado"
        "500":
          description: Erro no servidor
    delete:
      summary: Excluir uma conta de usuário pelo id
      parameters:
      - name: id
        in: path
        description: id da conta do usuário
        required: true
        style: simple
        explode: false
        schema:
          type: integer
      - name: token
        in: header
        description: Token JWT no header
        required: true
        style: simple
        explode: false
        schema:
          type: array
          items:
            type: string
            format: string
        example: ijMqSfD6+grE5PhMqz0cWcUU1+h+OZ7lbaFPRX2ym1bqCEe/1Fvjbq1paWSW80fip723tL+E1m0r7vLjdwMabcn7wAfUS6TSgj2qA5yF2YA++L/lEFnPDrFAF/rOt36q2Emi6ABf0fn21SE6zKIGX6PjGK+j7wkb9GayN4KUYynHclvIpL9TWXxRLsMEww9t8H8TMOfLaYo/aJtS/5cNMOlFCodf85WRlyAwUEfnwiXDbng1SoGmos8RR8njyLOoi8JCostvlOobdjpt34hgrhDSs/CyS91nUHbOU6hnxiQWkfuT5+cV/feN3gWd6BGs3Yxmxhkcg0iaYaJUNF5U1c8zzG/yqmHsk/evvN3MQM6S9BKyE4kP8rHoeK0rAQJzeQe9hwlCMpy+lB4WAcrwv04y7hrGyBOJOj5nDeRS8ruvJdtIrPqRz7lOEODuQ5MafbLfw9OT/+lml7dyfRwZkjuaoql9qYcGqkf+n2XBYkBVrQrmbwBVEF2VrdaDVVGjyPKwvOKUFzu8ao+ut6vlOdtvtDN152NSiiewubtMJWelxamppaYVLWlYIT2eTnasuKuyrw0Z4tLttktq2p0hkCRqjTeC5zWC7EIqN/p7gYU+vBRC3OhVS2FrTWaM+5upZvrbNPLLUgZhOgIogbGDUklJ7Z7zUpXpVKrJ+8LSgCxeRoiKPNWSCbU8PxJIGd/zOFHh4Rzp4GHNGfThDYgjkK80y3ct4R4hjR/aiho9k/g=
      responses:
        "204":
          description: Sem conteúdo
        "400":
          description: Dados do request enviados incorretos
        "401":
          description: "Token inválido, inexixtente ou expirado"
        "404":
          description: "Recurso {id} não encontado"
        "500":
          description: Erro no servidor
components:
  schemas:
    body_response:
      required:
      - dateBirth
      - email
      - firstName
      - gender
      - id
      - lastName
      - phoneNumber
      type: object
      properties:
        id:
          type: integer
          example: 1
        firstName:
          type: string
          example: Firt
        lastName:
          type: string
          example: Last
        email:
          type: string
          format: email
          example: admin@admin.com
        phoneNumber:
          type: number
        dateBirth:
          type: string
          format: date
        gender:
          type: string
          example: M
          enum:
          - M
          - F
    body_request:
      required:
      - dateBirth
      - email
      - firstName
      - gender
      - lastName
      - password
      - phoneNumber
      type: object
      properties:
        firstName:
          type: string
          example: Firt
        lastName:
          type: string
          example: Last
        email:
          type: string
          format: email
          example: admin@admin.com
        password:
          type: string
          format: password
          example: "123"
        phoneNumber:
          type: number
        dateBirth:
          type: string
          format: date
        gender:
          type: string
          example: M
          enum:
          - M
          - F
